/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    projects: Project;
    media: Media;
    users: User;
    inquiries: Inquiry;
    updates: Update;
    builds: Build;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    builds: BuildsSelect<false> | BuildsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "home", "about". The site fetches pages by this.
   */
  slug: string;
  /**
   * Add, reorder, or remove sections. Editing here changes content only — never the design.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            subtext?: string | null;
            layout?: ('left' | 'centered') | null;
            size?: ('full' | 'compact') | null;
            ctas?:
              | {
                  label?: string | null;
                  href?: string | null;
                  variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Structural layout — same content, different skeleton.
             */
            expression?: ('classic' | 'editorial' | 'statement') | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  icon?:
                    | (
                        | 'check'
                        | 'star'
                        | 'shield'
                        | 'zap'
                        | 'clock'
                        | 'users'
                        | 'wrench'
                        | 'mail'
                        | 'globe'
                        | 'layers'
                        | 'home'
                        | 'fence'
                        | 'map'
                        | 'phone'
                        | 'droplet'
                        | 'wind'
                        | 'message'
                        | 'whatsapp'
                      )
                    | null;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Structural layout — same content, different skeleton.
             */
            expression?: ('cards' | 'list' | 'columns') | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            items?:
              | {
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: string | null;
            image?: (number | null) | Media;
            imageAlt?: string | null;
            layout?: ('image-right' | 'image-left') | null;
            cta?: {
              label?: string | null;
              href?: string | null;
              variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
            };
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  company?: string | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            columns?: ('2' | '3' | '4') | null;
            aspect?: ('1 / 1' | '4 / 3' | '3 / 4' | '16 / 9') | null;
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            single?: boolean | null;
            items?:
              | {
                  q: string;
                  a: string;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            plans?:
              | {
                  badge?: string | null;
                  tag?: string | null;
                  name?: string | null;
                  price: string;
                  period?: string | null;
                  description?: string | null;
                  note?: string | null;
                  features?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  featured?: boolean | null;
                  total?: {
                    label?: string | null;
                    /**
                     * e.g. "$950" — shown as the computed total line.
                     */
                    amount?: string | null;
                  };
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                    variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingPlans';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            columns?: ('1' | '2') | null;
            services?:
              | {
                  name: string;
                  description?: string | null;
                  price?: string | null;
                  from?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceList';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            hours?:
              | {
                  day: string;
                  time?: string | null;
                  closed?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            mapEmbedUrl?: string | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hoursLocation';
          }
        | {
            eyebrow?: string | null;
            headline: string;
            subtext?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
              variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
            };
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            email?: string | null;
            phone?: string | null;
            showForm?: boolean | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional muted footnote card under the list.
             */
            note?: string | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            /**
             * The newsletter vendor's form URL (Brevo/MailerLite/Buttondown). The vendor account is in the client's name.
             */
            action: string;
            /**
             * Input name the vendor expects: Buttondown "email", Brevo "EMAIL", MailerLite "fields[email]".
             */
            emailField?: string | null;
            buttonLabel?: string | null;
            disclaimer?: string | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSignup';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            content_html?: string | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Raw HTML/embed, rendered as-is. Admin-only.
             */
            html?: string | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'customHtml';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'configurator';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            columns?: ('2' | '3' | '4') | null;
            /**
             * Small label above each card's areas, e.g. "Areas we serve".
             */
            serveLabel?: string | null;
            locations?:
              | {
                  name: string;
                  image?: (number | null) | Media;
                  label?: string | null;
                  areas?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'locationGrid';
          }
        | {
            eyebrow?: string | null;
            headline?: string | null;
            subtext?: string | null;
            columns?: ('2' | '3' | '4') | null;
            callout?: string | null;
            methods?:
              | {
                  icon?:
                    | (
                        | 'check'
                        | 'star'
                        | 'shield'
                        | 'zap'
                        | 'clock'
                        | 'users'
                        | 'wrench'
                        | 'mail'
                        | 'globe'
                        | 'layers'
                        | 'home'
                        | 'fence'
                        | 'map'
                        | 'phone'
                        | 'droplet'
                        | 'wind'
                        | 'message'
                        | 'whatsapp'
                      )
                    | null;
                  name?: string | null;
                  value: string;
                  href: string;
                  note?: string | null;
                  cta?: string | null;
                  external?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            variant?: ('default' | 'alt' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactMethods';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            align?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'titleBlock';
          }
        | {
            variant?: ('note' | 'tip' | 'warning' | 'info') | null;
            /**
             * Optional — overrides the default variant label ("Note", "Tip", …).
             */
            label?: string | null;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            language?:
              | (
                  | 'text'
                  | 'javascript'
                  | 'jsx'
                  | 'typescript'
                  | 'tsx'
                  | 'html'
                  | 'css'
                  | 'scss'
                  | 'json'
                  | 'yaml'
                  | 'toml'
                  | 'graphql'
                  | 'sql'
                  | 'python'
                  | 'bash'
                  | 'shell'
                  | 'lua'
                  | 'ruby'
                  | 'php'
                  | 'csharp'
                  | 'cpp'
                  | 'c'
                  | 'rust'
                  | 'go'
                  | 'zig'
                  | 'swift'
                  | 'kotlin'
                  | 'java'
                  | 'glsl'
                  | 'hlsl'
                  | 'wgsl'
                  | 'gdscript'
                  | 'vue'
                  | 'markdown'
                  | 'dockerfile'
                  | 'solidity'
                )
              | null;
            /**
             * Optional filename / context label shown in the header.
             */
            title?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeBlock';
          }
        | {
            image_src: number | Media;
            alt?: string | null;
            caption?: string | null;
            size?: ('normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            heading?: string | null;
            facts?:
              | {
                  /**
                   * The big stat: "4", "200+", "8GB".
                   */
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Leave empty to auto-fit to the fact count.
             */
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'factGrid';
          }
        | {
            /**
             * Optional heading above the strip.
             */
            label?: string | null;
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'screenshotGallery';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            /**
             * URL to the .mp4 file (H.264).
             */
            video_mp4: string;
            /**
             * Optional .webm (VP9) — preferred by Chrome/Firefox.
             */
            video_webm?: string | null;
            poster_src?: (number | null) | Media;
            caption?: string | null;
            aspect_ratio?: ('16/9' | '21/9' | '4/3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoPlayer';
          }
        | {
            /**
             * One block for the left column.
             */
            left?:
              | (
                  | {
                      variant?: ('note' | 'tip' | 'warning' | 'info') | null;
                      /**
                       * Optional — overrides the default variant label ("Note", "Tip", …).
                       */
                      label?: string | null;
                      body: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'callout';
                    }
                  | {
                      language?:
                        | (
                            | 'text'
                            | 'javascript'
                            | 'jsx'
                            | 'typescript'
                            | 'tsx'
                            | 'html'
                            | 'css'
                            | 'scss'
                            | 'json'
                            | 'yaml'
                            | 'toml'
                            | 'graphql'
                            | 'sql'
                            | 'python'
                            | 'bash'
                            | 'shell'
                            | 'lua'
                            | 'ruby'
                            | 'php'
                            | 'csharp'
                            | 'cpp'
                            | 'c'
                            | 'rust'
                            | 'go'
                            | 'zig'
                            | 'swift'
                            | 'kotlin'
                            | 'java'
                            | 'glsl'
                            | 'hlsl'
                            | 'wgsl'
                            | 'gdscript'
                            | 'vue'
                            | 'markdown'
                            | 'dockerfile'
                            | 'solidity'
                          )
                        | null;
                      /**
                       * Optional filename / context label shown in the header.
                       */
                      title?: string | null;
                      code: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'codeBlock';
                    }
                  | {
                      image_src: number | Media;
                      alt?: string | null;
                      caption?: string | null;
                      size?: ('normal' | 'wide') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'imageBlock';
                    }
                  | {
                      heading?: string | null;
                      facts?:
                        | {
                            /**
                             * The big stat: "4", "200+", "8GB".
                             */
                            value: string;
                            label: string;
                            description?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      /**
                       * Leave empty to auto-fit to the fact count.
                       */
                      columns?: ('2' | '3' | '4') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'factGrid';
                    }
                )[]
              | null;
            /**
             * One block for the right column.
             */
            right?:
              | (
                  | {
                      variant?: ('note' | 'tip' | 'warning' | 'info') | null;
                      /**
                       * Optional — overrides the default variant label ("Note", "Tip", …).
                       */
                      label?: string | null;
                      body: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'callout';
                    }
                  | {
                      language?:
                        | (
                            | 'text'
                            | 'javascript'
                            | 'jsx'
                            | 'typescript'
                            | 'tsx'
                            | 'html'
                            | 'css'
                            | 'scss'
                            | 'json'
                            | 'yaml'
                            | 'toml'
                            | 'graphql'
                            | 'sql'
                            | 'python'
                            | 'bash'
                            | 'shell'
                            | 'lua'
                            | 'ruby'
                            | 'php'
                            | 'csharp'
                            | 'cpp'
                            | 'c'
                            | 'rust'
                            | 'go'
                            | 'zig'
                            | 'swift'
                            | 'kotlin'
                            | 'java'
                            | 'glsl'
                            | 'hlsl'
                            | 'wgsl'
                            | 'gdscript'
                            | 'vue'
                            | 'markdown'
                            | 'dockerfile'
                            | 'solidity'
                          )
                        | null;
                      /**
                       * Optional filename / context label shown in the header.
                       */
                      title?: string | null;
                      code: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'codeBlock';
                    }
                  | {
                      image_src: number | Media;
                      alt?: string | null;
                      caption?: string | null;
                      size?: ('normal' | 'wide') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'imageBlock';
                    }
                  | {
                      heading?: string | null;
                      facts?:
                        | {
                            /**
                             * The big stat: "4", "200+", "8GB".
                             */
                            value: string;
                            label: string;
                            description?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      /**
                       * Leave empty to auto-fit to the fact count.
                       */
                      columns?: ('2' | '3' | '4') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'factGrid';
                    }
                )[]
              | null;
            split?: ('50/50' | '60/40' | '40/60' | '67/33' | '33/67') | null;
            align?: ('start' | 'center' | 'stretch') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sideBySide';
          }
        | {
            heading?: string | null;
            cards?:
              | {
                  title: string;
                  category?: string | null;
                  /**
                   * Slides up on hover.
                   */
                  description?: string | null;
                  image_src?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Leave empty to auto-fit to the card count.
             */
            columns?: ('2' | '3' | '4') | null;
            /**
             * Card height in px (default 280).
             */
            card_height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentCards';
          }
        | {
            image_src?: (number | null) | Media;
            /**
             * Optional .mp4 URL — plays autoplay/muted/loop instead of the image.
             */
            video_src?: string | null;
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            platforms?:
              | {
                  platform:
                    | 'godot'
                    | 'blender'
                    | 'windows'
                    | 'macos'
                    | 'linux'
                    | 'itch'
                    | 'steam'
                    | 'gumroad'
                    | 'unreal'
                    | 'unity';
                  id?: string | null;
                }[]
              | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  /**
                   * Leave empty for the component default.
                   */
                  variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
                  /**
                   * Solid variant only — fills with the theme color instead of white.
                   */
                  lava?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            flip?: boolean | null;
            media_fit?: ('cover' | 'contain') | null;
            /**
             * CSS background for the media panel (useful with "contain").
             */
            media_bg?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureSpotlight';
          }
        | {
            image_src: number | Media;
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            align?: ('left' | 'center') | null;
            /**
             * CSS min-height, e.g. "520px" (the default).
             */
            min_height?: string | null;
            cta_label?: string | null;
            cta_href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cinematicBanner';
          }
        | {
            /**
             * Optional .mp4 URL — plays autoplay/muted/loop.
             */
            video_src?: string | null;
            /**
             * Video poster, or standalone background if no video.
             */
            image_src?: (number | null) | Media;
            eyebrow?: string | null;
            title: string;
            subtitle?: string | null;
            actions?:
              | {
                  label: string;
                  href?: string | null;
                  /**
                   * Leave empty for the component default.
                   */
                  variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
                  /**
                   * Solid variant only — fills with the theme color instead of white.
                   */
                  lava?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            align?: ('left' | 'center') | null;
            show_scroll?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cinematicHero';
          }
        | {
            back_href?: string | null;
            back_label?: string | null;
            eyebrow?: string | null;
            title: string;
            /**
             * Expanded full name below the title.
             */
            subtitle?: string | null;
            abstract?: string | null;
            status?: ('released' | 'in_dev' | 'research' | 'live' | 'collab') | null;
            tags?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional collaborator line, e.g. "with NU AERO".
             */
            collab?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'labHero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            milestones?:
              | {
                  label: string;
                  description?: string | null;
                  status?: ('done' | 'in_progress' | 'planned' | 'cut') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'roadmapBlock';
          }
        | {
            /**
             * Leave empty for the default "Changelog".
             */
            heading?: string | null;
            entries?:
              | {
                  version: string;
                  date?: string | null;
                  title?: string | null;
                  changes?:
                    | {
                        type?: ('added' | 'fixed' | 'changed' | 'breaking' | 'removed') | null;
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'changelogBlock';
          }
        | {
            /**
             * Leave empty for the default "System Requirements".
             */
            heading?: string | null;
            minimum?: {
              os?: string | null;
              cpu?: string | null;
              gpu?: string | null;
              ram?: string | null;
              storage?: string | null;
              notes?: string | null;
            };
            recommended?: {
              os?: string | null;
              cpu?: string | null;
              gpu?: string | null;
              ram?: string | null;
              storage?: string | null;
              notes?: string | null;
            };
            /**
             * e.g. "Tested on Windows 11, RTX 3080".
             */
            tested_on?: string | null;
            /**
             * e.g. "PC only · Mac support planned 2025".
             */
            platform_note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'systemRequirements';
          }
        | {
            heading?: string | null;
            assets?:
              | {
                  name: string;
                  /**
                   * e.g. "3D Character", "Texture Pack".
                   */
                  category?: string | null;
                  preview_src?: (number | null) | Media;
                  file_url: string;
                  file_type?: ('glb' | 'fbx' | 'obj' | 'blend' | 'png' | 'psd' | 'zip' | 'svg' | 'mp3' | 'wav') | null;
                  /**
                   * e.g. "4.2 MB".
                   */
                  file_size?: string | null;
                  license?: ('free' | 'cc0' | 'attribution' | 'patreon') | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'assetGrid';
          }
        | {
            heading?: string | null;
            caption?: string | null;
            nodes?:
              | {
                  /**
                   * Short unique key, e.g. "player" — referenced by other nodes' Parent ID.
                   */
                  node_id: string;
                  /**
                   * Another node's Node ID. Leave blank for root nodes.
                   */
                  parent_id?: string | null;
                  label: string;
                  /**
                   * Optional badge, e.g. "GameObject", "Camera", "Script".
                   */
                  type?: string | null;
                  /**
                   * Inline annotation, e.g. "(disabled)", "← entry".
                   */
                  note?: string | null;
                  /**
                   * Lower numbers first within the same parent.
                   */
                  order?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hierarchyBlock';
          }
        | {
            heading?: string | null;
            caption?: string | null;
            layout?: ('hub' | 'linear' | 'tree') | null;
            /**
             * Hub layout only — the Node ID of the central orchestrator.
             */
            center_id?: string | null;
            node_size?: ('default' | 'compact' | 'wide') | null;
            nodes?:
              | {
                  node_id: string;
                  label: string;
                  description?: string | null;
                  role?: ('orchestrator' | 'reader' | 'processor' | 'renderer' | 'writer' | 'utility') | null;
                  badge?: string | null;
                  id?: string | null;
                }[]
              | null;
            edges?:
              | {
                  /**
                   * Node ID.
                   */
                  from: string;
                  /**
                   * Node ID.
                   */
                  to: string;
                  label?: string | null;
                  bidirectional?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'architectureBlock';
          }
        | {
            title: string;
            description?: string | null;
            /**
             * Loaded in the iframe only after the visitor clicks Launch.
             */
            embed_url: string;
            poster_src?: (number | null) | Media;
            launch_label?: string | null;
            /**
             * Small disclaimer, e.g. "Requires WebGL · ~45 MB".
             */
            warning?: string | null;
            /**
             * Iframe height in px (default 620).
             */
            height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embeddedApp';
          }
        | {
            /**
             * Leave empty for the default "Available Now".
             */
            heading?: string | null;
            /**
             * e.g. "$9.99", "Free", "Pay What You Want".
             */
            price?: string | null;
            /**
             * e.g. "One-time purchase · DRM-free".
             */
            price_note?: string | null;
            links?:
              | {
                  label: string;
                  href?: string | null;
                  /**
                   * Leave empty for the component default.
                   */
                  variant?: ('solid' | 'ghost' | 'ghost-bordered') | null;
                  /**
                   * Optional icon key, e.g. "steam", "itch".
                   */
                  icon_slug?: string | null;
                  id?: string | null;
                }[]
              | null;
            patreon_href?: string | null;
            /**
             * Leave empty for the default "Support on Patreon".
             */
            patreon_label?: string | null;
            /**
             * Fine print below everything.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingCTA';
          }
        | {
            size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  cover?: (number | null) | Media;
  excerpt?: string | null;
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — the project this guide/devlog is about.
   */
  project?: (number | null) | Project;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  tagline?: string | null;
  cover?: (number | null) | Media;
  status?: ('active' | 'shipped' | 'archived') | null;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Requests from the website. Reply by email, then set the status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  /**
   * One line — what they asked for.
   */
  summary?: string | null;
  name?: string | null;
  email: string;
  business?: string | null;
  message?: string | null;
  source: 'plan-finder' | 'configurator' | 'estimator' | 'contact';
  /**
   * Full selection payload from the form.
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'replied' | 'closed') | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Status center feed shown on the site's /status page. Post stack updates, feature launches, announcements, and incidents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  title: string;
  category: 'stack' | 'feature' | 'announcement' | 'incident' | 'maintenance';
  /**
   * Short description shown under the title.
   */
  body?: string | null;
  /**
   * Optional call-to-action label.
   */
  linkLabel?: string | null;
  /**
   * Optional link URL for the CTA.
   */
  linkHref?: string | null;
  /**
   * Pin to the top — e.g. an active incident or headline announcement.
   */
  pinned?: boolean | null;
  /**
   * Shown on the entry + used for ordering (newest first).
   */
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Work-page showcase of sites in development. Upload a screenshot + a line of text; newest shows first on /work.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds".
 */
export interface Build {
  id: number;
  title: string;
  status: 'in-development' | 'published';
  /**
   * Cover screenshot — the thumbnail shown on the card.
   */
  image: number | Media;
  /**
   * More screenshots — shown in the popup gallery when the card is clicked. Add as many as you like.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Short label under the title, e.g. "Hair salon" or "Restaurant".
   */
  kind?: string | null;
  /**
   * Live site link — OPTIONAL. Leave blank for private clients.
   */
  url?: string | null;
  /**
   * One or two sentences about the build.
   */
  blurb?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'builds';
        value: number | Build;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              layout?: T;
              size?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              expression?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              expression?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              image?: T;
              imageAlt?: T;
              layout?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    company?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              columns?: T;
              aspect?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              single?: T;
              items?:
                | T
                | {
                    q?: T;
                    a?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        pricingPlans?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              plans?:
                | T
                | {
                    badge?: T;
                    tag?: T;
                    name?: T;
                    price?: T;
                    period?: T;
                    description?: T;
                    note?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    featured?: T;
                    total?:
                      | T
                      | {
                          label?: T;
                          amount?: T;
                        };
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          variant?: T;
                        };
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        serviceList?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              columns?: T;
              services?:
                | T
                | {
                    name?: T;
                    description?: T;
                    price?: T;
                    from?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        hoursLocation?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              hours?:
                | T
                | {
                    day?: T;
                    time?: T;
                    closed?: T;
                    id?: T;
                  };
              address?: T;
              phone?: T;
              email?: T;
              mapEmbedUrl?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              email?: T;
              phone?: T;
              showForm?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              note?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        newsletterSignup?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              action?: T;
              emailField?: T;
              buttonLabel?: T;
              disclaimer?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              content_html?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        customHtml?:
          | T
          | {
              html?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        configurator?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        locationGrid?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              columns?: T;
              serveLabel?: T;
              locations?:
                | T
                | {
                    name?: T;
                    image?: T;
                    label?: T;
                    areas?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contactMethods?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subtext?: T;
              columns?: T;
              callout?: T;
              methods?:
                | T
                | {
                    icon?: T;
                    name?: T;
                    value?: T;
                    href?: T;
                    note?: T;
                    cta?: T;
                    external?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        titleBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              variant?: T;
              label?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        codeBlock?:
          | T
          | {
              language?: T;
              title?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image_src?: T;
              alt?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        factGrid?:
          | T
          | {
              heading?: T;
              facts?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        screenshotGallery?:
          | T
          | {
              label?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoPlayer?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              video_mp4?: T;
              video_webm?: T;
              poster_src?: T;
              caption?: T;
              aspect_ratio?: T;
              id?: T;
              blockName?: T;
            };
        sideBySide?:
          | T
          | {
              left?:
                | T
                | {
                    callout?:
                      | T
                      | {
                          variant?: T;
                          label?: T;
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    codeBlock?:
                      | T
                      | {
                          language?: T;
                          title?: T;
                          code?: T;
                          id?: T;
                          blockName?: T;
                        };
                    imageBlock?:
                      | T
                      | {
                          image_src?: T;
                          alt?: T;
                          caption?: T;
                          size?: T;
                          id?: T;
                          blockName?: T;
                        };
                    factGrid?:
                      | T
                      | {
                          heading?: T;
                          facts?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                description?: T;
                                id?: T;
                              };
                          columns?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              right?:
                | T
                | {
                    callout?:
                      | T
                      | {
                          variant?: T;
                          label?: T;
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    codeBlock?:
                      | T
                      | {
                          language?: T;
                          title?: T;
                          code?: T;
                          id?: T;
                          blockName?: T;
                        };
                    imageBlock?:
                      | T
                      | {
                          image_src?: T;
                          alt?: T;
                          caption?: T;
                          size?: T;
                          id?: T;
                          blockName?: T;
                        };
                    factGrid?:
                      | T
                      | {
                          heading?: T;
                          facts?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                description?: T;
                                id?: T;
                              };
                          columns?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              split?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        contentCards?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    category?: T;
                    description?: T;
                    image_src?: T;
                    id?: T;
                  };
              columns?: T;
              card_height?: T;
              id?: T;
              blockName?: T;
            };
        featureSpotlight?:
          | T
          | {
              image_src?: T;
              video_src?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              platforms?:
                | T
                | {
                    platform?: T;
                    id?: T;
                  };
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    lava?: T;
                    id?: T;
                  };
              flip?: T;
              media_fit?: T;
              media_bg?: T;
              id?: T;
              blockName?: T;
            };
        cinematicBanner?:
          | T
          | {
              image_src?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              align?: T;
              min_height?: T;
              cta_label?: T;
              cta_href?: T;
              id?: T;
              blockName?: T;
            };
        cinematicHero?:
          | T
          | {
              video_src?: T;
              image_src?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    lava?: T;
                    id?: T;
                  };
              align?: T;
              show_scroll?: T;
              id?: T;
              blockName?: T;
            };
        labHero?:
          | T
          | {
              back_href?: T;
              back_label?: T;
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              abstract?: T;
              status?: T;
              tags?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              collab?: T;
              id?: T;
              blockName?: T;
            };
        roadmapBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              milestones?:
                | T
                | {
                    label?: T;
                    description?: T;
                    status?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        changelogBlock?:
          | T
          | {
              heading?: T;
              entries?:
                | T
                | {
                    version?: T;
                    date?: T;
                    title?: T;
                    changes?:
                      | T
                      | {
                          type?: T;
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        systemRequirements?:
          | T
          | {
              heading?: T;
              minimum?:
                | T
                | {
                    os?: T;
                    cpu?: T;
                    gpu?: T;
                    ram?: T;
                    storage?: T;
                    notes?: T;
                  };
              recommended?:
                | T
                | {
                    os?: T;
                    cpu?: T;
                    gpu?: T;
                    ram?: T;
                    storage?: T;
                    notes?: T;
                  };
              tested_on?: T;
              platform_note?: T;
              id?: T;
              blockName?: T;
            };
        assetGrid?:
          | T
          | {
              heading?: T;
              assets?:
                | T
                | {
                    name?: T;
                    category?: T;
                    preview_src?: T;
                    file_url?: T;
                    file_type?: T;
                    file_size?: T;
                    license?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hierarchyBlock?:
          | T
          | {
              heading?: T;
              caption?: T;
              nodes?:
                | T
                | {
                    node_id?: T;
                    parent_id?: T;
                    label?: T;
                    type?: T;
                    note?: T;
                    order?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        architectureBlock?:
          | T
          | {
              heading?: T;
              caption?: T;
              layout?: T;
              center_id?: T;
              node_size?: T;
              nodes?:
                | T
                | {
                    node_id?: T;
                    label?: T;
                    description?: T;
                    role?: T;
                    badge?: T;
                    id?: T;
                  };
              edges?:
                | T
                | {
                    from?: T;
                    to?: T;
                    label?: T;
                    bidirectional?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        embeddedApp?:
          | T
          | {
              title?: T;
              description?: T;
              embed_url?: T;
              poster_src?: T;
              launch_label?: T;
              warning?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        pricingCTA?:
          | T
          | {
              heading?: T;
              price?: T;
              price_note?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    icon_slug?: T;
                    id?: T;
                  };
              patreon_href?: T;
              patreon_label?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  excerpt?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  project?: T;
  content?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  cover?: T;
  status?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  summary?: T;
  name?: T;
  email?: T;
  business?: T;
  message?: T;
  source?: T;
  details?: T;
  status?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  body?: T;
  linkLabel?: T;
  linkHref?: T;
  pinned?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds_select".
 */
export interface BuildsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  image?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  kind?: T;
  url?: T;
  blurb?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}